### Ejercicio 1: Suma Matrices
Complete la implementación de la función suma_matrices para que devuelva como resultado la suma entre las dos matrices (arreglos numpy) pasados como parámetro (recordá verificar que los tamaños sean compatibles). 

In [2]:
import numpy as np

def suma_matrices(A, B):
  suma = np.array([A + B])
  if len(A) != len(B):
    print("Las matrices deben tener las mismas dimensiones")
  #if len(A) == len(B):
  else:
    return suma
  
# Ejemplo de uso
A = np.array([[1, 2,3], [4, 5, 6]])
B = np.array([[4, 2, 1], [4, 2, 1]])

# Llamar a la función
C = suma_matrices(A, B)

print("Resultado de la suma de matrices:")
print(C)

                                                                                                                                                    

Resultado de la suma de matrices:
[[[5 4 4]
  [8 7 7]]]


In [3]:
A = np.array([[1, 2,3], [4, 5, 6]])
A.shape 

(2, 3)

In [27]:
#@title Ejecuta esta celda para evaluar tu función
import numpy as np
A = np.array([
    [10,20,30],
    [40,50,60]
])

B = np.array([
    [10,50,30],
    [40,20,60]
])

C = np.array([
        [ 2,  3,  5,  -8],
        [4, 13, 17, -19],
        [23, 15, 31, 0]
])

D = np.array([
        [ 2,  3,  5,  7],
        [11, 13, 17, 19],
        [23, 29, 31, 37]
    ])

def test_suma(A,B,C,D):
  if( not (suma_matrices(A, B) == A + B).all()): raise ValueError("La suma entre A y B falla")
  try:
    suma_matrices(C, A)
    print("Tu función no contempla tamaños incompatibles a la hora de sumar" )
  except ValueError:
    print("Tu función suma_matrices está excelente")

test_suma(A,B,C,D)

Tu función suma_matrices está excelente


### Ejercicio 2
Complete la implementación de las funciones es_triangular_superior(), es_triangular_inferior() y es_diagonal() para que devuelvan verdadero o falso según corresponda. 

In [ ]:
# REVISAR CÓDIGO ESTÁ DE CHAT GPT
def es_triangular_superior(A): # Cuando todos los elementos por debajo de la diagonal son 0
  #complete con su código aquí
  # Verificar si A es una matriz cuadrada
    if A.shape[0] != A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada.")
    
    # Comprobar si todos los elementos debajo de la diagonal principal son cero
    for i in range(1, A.shape[0]):  # Desde la fila 1 hasta el final
        for j in range(i):  # Los elementos debajo de la diagonal (i > j)
            if A[i, j] != 0:
                return False
    return True
def es_triangular_inferior(A): # Cuando todos los elementos por encima de la diagonal son 0
  #complete con su código aquí  
 # Verificar que A es una matriz cuadrada
    if A.shape[0] != A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada.")
    
    # Comprobar si todos los elementos por encima de la diagonal principal son cero
    for i in range(A.shape[0] - 1):  # Hasta la penúltima fila
        for j in range(i + 1, A.shape[1]):  # Los elementos por encima de la diagonal (i < j)
            if A[i, j] != 0:
                return False
    return True
def es_diagonal(A): # Cuando todos los elementos fuera de la diagonal principal son 0
  #complete con su código aquí
 # Verificar que A es una matriz cuadrada
    if A.shape[0] != A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada.")
    
    # Comprobar si todos los elementos fuera de la diagonal son cero
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if i != j and A[i, j] != 0:
                return False
    return True

# Ejemplo de uso
A1 = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])  # Triangular superior
A2 = np.array([[1, 0, 0], [4, 5, 0], [7, 8, 9]])  # Triangular inferior
A3 = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])  # Diagonal

print("A1 es triangular superior:", es_triangular_superior(A1))  # True
print("A2 es triangular inferior:", es_triangular_inferior(A2))  # True
print("A3 es diagonal:", es_diagonal(A3))  # True

A1 es triangular superior: True
A2 es triangular inferior: True
A3 es diagonal: True


In [14]:
#@title Ejecuta esta celda para evaluar tu función
import numpy as np
A = np.array([[4, 1, 0],
       [0, 5, 0],
       [0, 0, 6]])

B = np.array([[4, 0, 0],
       [1, 5, 0],
       [3, 0, 6]])

C = np.array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

D = np.array([
        [ 2,  3,  5,  7],
        [11, 13, 17, 19],
        [23, 29, 31, 37]
    ])

def test(A,B,C,D):
  if not es_triangular_superior(A): raise ValueError("tu función falla al detectar matrices triangulares superiores")
  if not es_triangular_inferior(B): raise ValueError("tu función falla al detectar matrices triangulares inferiores")
  if not es_diagonal(C): raise ValueError("tu función falla al detectar matrices diagonales")
  if es_triangular_superior(B) or es_triangular_superior(D): raise ValueError("tu función indica como matrices triangulares superiores algunas matrices que no lo son")
  if es_triangular_inferior(A) or es_triangular_inferior(D): raise ValueError("tu función indica como matrices triangulares inferiores algunas matrices que no lo son")
  if es_diagonal(A) or es_diagonal(D) or es_diagonal(B): raise ValueError("tu función indica como matrices diagonales algunas matrices que no lo son")
  print("Las tres funciones están excelentes!")
test(A,B,C,D)

ValueError: La matriz debe ser cuadrada.

### Ejercicio 3
Complete la implementación de la función producto_matrices para que devuelva como resultado la multiplicación entre las dos matrices (arreglos numpy) pasados como parámetro (recuerda verificar que los tamaños sean compatibles). 

In [18]:
import numpy as np

def producto_matrices(a, b):
    """
    Realiza la multiplicación de dos matrices A y B.
    La multiplicación solo es posible si el número de columnas de A
    es igual al número de filas de B.
    """
    # Verificar si las dimensiones son compatibles para la multiplicación
    if a.shape[1] != b.shape[0]:
        raise ValueError("Las matrices tiene que ser del mismo tamaño")
    
    # Multiplicación de matrices usando np.dot() 
    producto = np.dot(a, b)
    
    return producto

# Ejemplo de uso:
a = np.array([[1, 2], [3, 4]])  # Matriz 2x2
b = np.array([[5, 6], [7, 8]])  # Matriz 2x2

# Llamamos a la función
C = producto_matrices(a, b)

print("El resultado de la multiplicación A x B:")
print(C)


El resultado de la multiplicación A x B:
[[19 22]
 [43 50]]


In [19]:
#@title Ejecuta esta celda para evaluar tu función
import numpy as np
A = np.array([
    [10,20,30],
    [40,50,60]
])

B = np.array([
    [10,50,30],
    [40,20,60]
])

C = np.array([
        [ 2,  3,  5,  -8],
        [4, 13, 17, -19],
        [23, 15, 31, 0]
])

D = np.array([
        [ 2,  3,  5,  7],
        [11, 13, 17, 19],
        [23, 29, 31, 37]
    ])
def test_producto(A,B,C,D):
  if( not (producto_matrices(A, C) == A.dot(C)).all()): raise ValueError("La multiplicación entre A y C falla")
  try:
    producto_matrices(C, A)
    print("Tu función no contempla tamaños incompatibles a la hora de multiplicar" )
  except ValueError:
    print("Tu función producto_matrices está excelente")

test_producto(A,B,C,D)

def test_suma(A,B,C,D):
  if( not (suma_matrices(A, B) == A + B).all()): raise ValueError("La suma entre A y B falla")
  try:
    producto_matrices(C, A)
    print("Tu función no contempla tamaños incompatibles a la hora de sumar" )
  except ValueError:
    print("Tu función suma_matrices está excelente")

Tu función producto_matrices está excelente
