![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [8]:
my_array = np.arange(10)
print(my_array)

print(my_array[9], my_array[7], my_array[5], my_array[3], my_array[1])


[0 1 2 3 4 5 6 7 8 9]
9 7 5 3 1


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
# slice que empieza en el indice 8 y termina en el 6, hacia atras de uno en uno (-1)
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [ ]:
# Del 2 hasta el final de uno en uno hacia atrás
print(my_array[2::-1])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [ ]:
matriz = np.arange(1, 21).reshape(4, 5) # 4 filas, 5 columnas
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
matriz_invertida = matriz[::-1, ::-1]
print(matriz_invertida)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
mini_matriz = matriz[:2, :2] #Slicing
print(mini_matriz)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [15]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
ejercicio_6 = matriz[::2, ::2] # Primero el slicing de las filass y luego el de las columnas
print(ejercicio_6)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [16]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# Slicing de las filas 1, 2 y 3 y luego se invierten
ejercicio_7 = matriz[:3, ::-1]
print(ejercicio_7)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [22]:
ejercicio_8 = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(ejercicio_8)

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


In [ ]:
# Primera manera (máscara booleana)
primera_manera = ejercicio_8 == "Loro" # True donde ponga loro
mascara_booleana = ejercicio_8[primera_manera] # Filtramos solo los true
print(mascara_booleana)

['Loro' 'Loro']


In [24]:
# Segunda manera (np.where())
indices = np.where(ejercicio_8 == "Loro")[0]
where = ejercicio_8[indices]
print(where)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [26]:
ejercicio_9 = np.arange(1, 21) # Creo la secuencia
transformacion = ejercicio_9.reshape(2, 5, 2) # La transformo en dos matrices de 5x2 cada una
print(transformacion)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [27]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
ejercicio_10 = matriz[::-1, ::-1] # Invertir la matriz
print(ejercicio_10)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [29]:
ejercicio_11 = np.zeros(10)
print(ejercicio_11)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
# Verificar cuanta memoria ocupa

import sys
print("El array ocupa: ", sys.getsizeof(ejercicio_11), "bytes de memoria")

El array ocupa:  192 bytes de memoria


In [32]:
ejercicio_11 [3] = 1
print(ejercicio_11)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [34]:
ejercicio_12 = list(range(10, 50))
print(ejercicio_12)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [35]:
# Invertir el vector
ejercicio_12.reverse()
print(ejercicio_12)

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [37]:
ejercicio_13 = [1, 2, 0, 0, 4, 0]
indices = []

for i in range(len(ejercicio_13)):
    if ejercicio_13[i] != 0:
        indices.append(i)

print(indices)


[0, 1, 4]


In [ ]:
#Utilizando el método de numpy
ejercicio_13 = [1, 2, 0, 0, 4, 0]
indices = [i for i, valor in enumerate(ejercicio_13) if valor != 0]
print(indices)

[0, 1, 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
ejercicio_14 = np.random.randint(0, 98, size=(10, 10)) # Puedes colocar el máximo y el minimo que quieras
print(ejercicio_14)

[[61 42 24 11  3 58 92 32 86 24]
 [97 27 87 68 80 15 79 18 93 46]
 [ 4 83 89 69 14  4 72 71 71 78]
 [ 4 71 79 52 75 51  3 52  9 74]
 [94 91 57 61  5 54 20 37 56 63]
 [29 82 80 47 61 73  5 49 83 29]
 [73 13 88 29 55 93 71 55 91 94]
 [81  3 29 50 56 25 35 94 75 91]
 [34 43 80  8 41 18 51 64 40 85]
 [66 43 60 78 61 49 62 61 80 66]]


In [45]:
valor_minimo = np.min(ejercicio_14)
print(f'El valor mínimo es:{valor_minimo}')
valor_maximo = np.max(ejercicio_14)
print(f'El valor máximo es:{valor_maximo}')

El valor mínimo es:3
El valor máximo es:97


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [49]:
ejercicio_15 = np.random.randint(0, 51, size=30) # Creo el vector
media = np.mean(ejercicio_15) # Calculo la media
print(f'La media es: {media}')

La media es: 19.666666666666668


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [50]:
tamaño = 7

In [51]:
ejercicio_16 = np.zeros((tamaño, tamaño), dtype=int) # Todo el interior son ceros

ejercicio_16[0, :] = 1  # Unos en la primera fila
ejercicio_16[-1, :] = 1  # Unos en la última fila
ejercicio_16[:, 0] = 1  # Unos en la primera columna
ejercicio_16[:, -1] = 1  # Unos en la última columna

print(ejercicio_16)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [52]:
ejercicio_17 = np.zeros((8, 8), dtype=int) # Matriz de ceros (8x8)
print(ejercicio_17)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
ejercicio_17[::2, ::2] = 1  # Poner 1 en las posiciones de las filas y columnas pares
ejercicio_17[1::2, 1::2] = 1  # Poner 1 en las posiciones de las filas y columnas impares
print(ejercicio_17)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
# Crear un bloque de 2x2 con el patrón alternante (0 y 1)
bloque = np.array([[0, 1], [1, 0]])
# Replicar el bloque 4 veces en ambas direcciones (filas y columnas)
ejercicio_18 = np.tile(bloque, (4, 4))

print(ejercicio_18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [56]:
ejercicio_19 = np.random.randint(0, 101, size=(5, 5))
print(ejercicio_19)

[[ 27   9  16  84  47]
 [ 96  39  11  13  33]
 [ 50  70  91  71  91]
 [ 42  65 100  15 100]
 [ 80   2  38   5  22]]


In [57]:
media = np.mean(ejercicio_19) # calcula la media
desviacion_estandar = np.std(ejercicio_19) # calcula la desviación estandar
# Normalización de la matriz
matriz_normalizada = (ejercicio_19 - media) / desviacion_estandar

print(matriz_normalizada)

[[-0.66243726 -1.2124313  -0.99854473  1.07921052 -0.05133278]
 [ 1.44587322 -0.29577457 -1.15132085 -1.0902104  -0.47910592]
 [ 0.0403329   0.65143738  1.29309709  0.68199261  1.29309709]
 [-0.2041089   0.49866126  1.56809411 -1.02909996  1.56809411]
 [ 0.95698963 -1.42631787 -0.3263298  -1.3346522  -0.81521339]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [58]:
# Secuencia de numeros del 0 al 10
ejercicio_20 = np.arange(11)
print(ejercicio_20)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [60]:
# Donde los valores mayores que 3 y menos que 8 los cambia por -1
nuevo_array_1 = np.where((ejercicio_20 >= 3) & (ejercicio_20 <= 8), -1, ejercicio_20)
print(nuevo_array_1)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [61]:
# Array que niegue todos los elementos entre 3 y 8 (reemplaza esos valores por False)
nuevo_array_2 = ~( (ejercicio_20 >= 3) & (ejercicio_20 <= 8) )
print(nuevo_array_2)

[ True  True  True False False False False False False  True  True]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [67]:
import numpy as np
import random

In [62]:
# 1: Crear un tablero de 10x10 relleno de espacios
tablero = [[' ' for _ in range(10)] for _ in range(10)]

In [63]:
# 2: Posionar los barcos
# Barco de 2 posiciones: [(0,1), (1,1)]
tablero[0][1] = 'O'
tablero[1][1] = 'O'

# Barco de 4 posiciones: [(1,3), (1,4), (1,5), (1,6)]
tablero[1][3] = 'O'
tablero[1][4] = 'O'
tablero[1][5] = 'O'
tablero[1][6] = 'O'

In [64]:
# Imprimir el tablero
def imprimir_tablero(tablero):
    for fila in tablero:
        print(' '.join(fila))

In [65]:
# 3: Recibir un disparo en un barco (sustituir 'O' por 'X')
tablero[1][1] = 'X' # dispara en (1,1)

In [ ]:
# 4: Recibir un disparo en agua
tablero[0][0] = '-' # Dispara en (0,0)

In [68]:
# 5: Posicionar un barco de 4 posiciones de manera aleatoria
# Generamos una orientación aleatoria (N, S, E, O)
orientaciones = ['N', 'S', 'E', 'O']
orientacion_aleatoria = random.choice(orientaciones)

In [ ]:
def colocar_barco_aleatorio(tablero):
    direccion = random.choice(orientaciones)
    barco_colocado = False

    while not barco_colocado:
        if direccion == 'N' or direccion == 'S':  # Vertical
            fila = random.randint(0, 9)
            columna = random.randint(0, 9)

            if fila + 3 <= 9:  # Comprobamos si cabe hacia abajo
                for i in range(4):
                    if tablero[fila + i][columna] != ' ':
                        break
                else:
                    for i in range(4):
                        tablero[fila + i][columna] = 'O'
                    barco_colocado = True

        elif direccion == 'E' or direccion == 'O':  # Horizontal
            fila = random.randint(0, 9)
            columna = random.randint(0, 9)

            if columna + 3 <= 9:  # Comprobamos si cabe hacia la derecha
                for i in range(4):
                    if tablero[fila][columna + i] != ' ':
                        break
                else:
                    for i in range(4):
                        tablero[fila][columna + i] = 'O'
                    barco_colocado = True


In [ ]:
# Colocamos un barco aleatorio
colocar_barco_aleatorio(tablero)

# Imprimir el tablero después de las modificaciones
imprimir_tablero(tablero)